In [13]:
import torch
import numpy as np
import torch.nn as nn
import KddModel as kdd
import pandas as pd
from scipy.io import arff


In [19]:
kddtest=np.genfromtxt("../../data/nsl-kdd/KDDTest+.txt",dtype={"names":('duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','class','level'),
"formats":('f','S10','S16','S10','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','S20','f')},delimiter=',',usecols=range(42))
print(type(kddtest))
new=kddtest[0]
print(type(new))
print(new)

<class 'numpy.ndarray'>
<class 'numpy.void'>
(0., b'tcp', b'private', b'REJ', 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 229., 10., 0., 0., 1., 1., 0.04, 0.06, 0., 255., 10., 0.04, 0.06, 0., 0., 0., 0., 1., 1., b'neptune')


In [17]:
new=kdd.Kddset("KDDTrain+.txt",train=False)
for nd,nl in new:
    print(nd,nl)
    break
 
print(len(new))

tensor([[0.0000e+00, 1.0000e+00, 1.8000e+01, 1.0000e+01, 4.9100e+02, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.0000e+00, 2.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 1.5000e+02, 2.5000e+01, 1.7000e-01, 3.0000e-02, 1.7000e-01,
         0.0000e+00, 0.0000e+00, 0.0000e+00]]) 1
125973


In [16]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr>5)
arr[arr>5]=1
print(arr)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[1 2 3 4 5 1 1 1 1]
